<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://replica.mx/students"
           xmlns:tns="http://replica.mx/students"
           elementFormDefault="qualified">

  <xs:element name="getStudentRequest">
    <xs:complexType>
      <xs:sequence><xs:element name="id" type="xs:long"/></xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="getStudentResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="xs:long"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="course" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
